app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('', views.index),
    path('members/', include('members.urls'))
] + static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

app/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('',views.post_list, name='post-list'),
    path('<int:pk>/',views.post_detail, name='post-datail'),
]

app/members/models.py
from django.db import models

# Create your models here.

app/posts/models.py
from django.conf import settings
from django.db import models

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='post', blank=True)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

app/config/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect


def index(requset):
    return redirect('posts:post-list')

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect


#1 member.urls <- 'members/' 로 include 되도록 config.urls모듈에 추가
#2 path 구현 (URL: '/members/login/')
#3 path 와 이 view 연결
#4 일단 잘 나오는지 확인
#5 잘 나오면 form을 작성 (username, password를 받는 input 2개)
#6 form 작성 후에는 POST 방식 요청을 보내서 이 뷰에서 request.POST 에 요청이 잘 왔는지 확인
#7 일단은 받는 username, password 값을 HttpResponse에 보여주도록 한다.

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # 인증에 성공하면 posts:post-list로 이동
        # 실패하면 다시 members:login으로 이동

        # 받은 username
        user = authenticate(request, username=username, password=password)

        # 인증에 성공한 경우
        if user is not None:

            # 세션값을 만들어 DB에 저장하고, HTTP response의 Cookie에 해당값을 담아보내도록 하는
            # login() 함수를 실행한다.
            login(request, user)
            # 이후 post-list로 redirect
            return redirect('posts:post-list')
        # 인증에 실패한 경우 (username 또는 password가 틀린 경우
        else:
            # 다시 로그인 페이지로 redirect
            return redirect('members:login')
    # GET 요청일 경우
    else:
        # form 이 있는 template를 보여준다.
        return render(request, 'members/login.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:post-list')
    else:
        return redirect('posts:post-list')

app/posts/views.py
from .models import Post
from django.shortcuts import render



def post_list(requset):
    posts = Post.objects.all()
    context = {
        'posts':posts,
    }

    return render(requset, 'posts/post_list.html', context)


def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    context = {
        'posts':post,
        'pk':pk,
    }

    return render(request, 'posts/post_detail.html', context)

app/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Youn lab</title>
</head>
<body>
<h1>instargram</h1>
<div>
    {% if user.is_authenticated %}
        <form action="{% url 'members:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">로그아웃 하기</button>
        </form>
        {% else %}
        <a href="{% url 'members:login' %}"> 로그인하기 </a>
    {% endif %}
</div>
<div class="container">
    <div>
    {% block content %}
    {% endblock %}
    </div>
</div>

</body>
</html>

app/templates/members/login.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <label for="user_id">ID</label>
            <input type="text" id="user_id" name="username">
            <label for="user_pw">PW</label>
            <input type="password" id="user_pw" name="password">
            <button type="submit">Login</button>

        </form>
    </div>

{% endblock %}

app/templates/posts/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Youn lab</title>
</head>
<body>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

app/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>post detail</h1>
<p>{{ post }}</p>
{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}

<p>post list</p>
{% for post in posts %}
    <div>
        <div>{{ post.author.username }}</div>
        <div><img src="{{ post.photo.url }}" width="100%"> </div>
    </div>
{% endfor %}
{% endblock %}